#서비스 변경감지용 주석
server:
  port: 8000

spring:
  application:
    name: gateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins:

              - "http://localhost:5173" #사용자 프론트 서버
              - "http://localhost:9090" #관리자 프론트 로컬 서버
              - "http://playdata-orderservice4908.s3-website.ap-northeast-2.amazonaws.com" #AWS 정적 서버

            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers:
              - Content-Type
              - Authorization
              - X-Requested-With
            allow-credentials: true

      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: hello gateway!
            preLogger: false
            postLogger: true
      routes:
        - id: user-service
          #유레카 연동주소
#          uri: lb://USER-SERVICE
          #k8s 클러스터 내에서 다른 서비스를 지목하기 위한 DNS 명명 규칙.
          #<service-name>.<namespace>.svc.cluster.local:port
          uri: http://user-service.default.svc.cluster.local:8081
          predicates:
            - Path=/user-service/user/doLogin
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: http://user-service.default.svc.cluster.local:8081
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: product-service
          uri: http://product-service.default.svc.cluster.local:8082
          predicates:
            - Path=/product-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: ordering-service
          uri: http://ordering-service.default.svc.cluster.local:8083
          predicates:
            - Path=/ordering-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/ordering-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter










